#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 5017

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Microservices/BankAccount/BankAccountService.csproj", "Microservices/BankAccount/"]
RUN dotnet restore "Microservices/BankAccount/BankAccountService.csproj"
COPY . .
WORKDIR "/src/Microservices/BankAccount"
RUN dotnet build "BankAccountService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BankAccountService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BankAccountService.dll"]